# Site settings
title: Web Components
email: jpilgreen@kcstar.com

description:
  A collection of web components used by The Kansas City Star.

baseurl: /kcstar-webcomponents
url: http://pilgreen.github.io

# Build settings
markdown: kramdown
exclude: [bower.json, bower_components]
