# Site settings
title: Web Components
email: jpilgreen@kcstar.com

description:
  A collection of elements used by The Kansas City Star.

baseurl: /kcstar-webcomponents/
url: http://pilgreen.github.io

# Build settings
markdown: kramdown
